Repository norse/norse, pull requests merged in 2020-11, with the labels that each got.

#157 Fixes a bug where SequentialState throws if given list states
  norse/torch/module/sequential.py
  norse/torch/module/test/test_sequential.py
Labels: bug

#111 Fixes necessary to make pytype happy
  .github/workflows/pythonpackage.yml
  norse/benchmark/bindsnet_lif.py
  norse/benchmark/genn_lif.py
  norse/benchmark/main.py
  norse/benchmark/norse_lif.py
  norse/benchmark/plot.py
  norse/dataset/dvs_gesture.py
  norse/dataset/speech_commands.py
  norse/task/cartpole.py
  norse/task/cifar10.py
  norse/task/memory.py
  norse/task/mnist.py
  norse/task/speech_commands/run.py
  norse/torch/functional/__init__.py
  norse/torch/functional/coba_lif.py
  norse/torch/functional/encode.py
  norse/torch/functional/lif.py
  norse/torch/functional/lif_adex.py
  norse/torch/functional/lif_correlation.py
  norse/torch/functional/lif_ex.py
  norse/torch/functional/lif_mc.py
  norse/torch/functional/lif_mc_refrac.py
  norse/torch/functional/lif_refrac.py
  norse/torch/functional/logical.py
  norse/torch/functional/lsnn.py
  norse/torch/functional/regularization.py
  norse/torch/functional/stdp.py
  norse/torch/functional/stdp_sensor.py
  norse/torch/functional/superspike.py
  norse/torch/functional/test/test_regularization.py
  norse/torch/functional/threshold.py
  norse/torch/functional/tsodyks_makram.py
  norse/torch/module/coba_lif.py
  norse/torch/module/encode.py
  norse/torch/module/lif.py
  norse/torch/module/lif_adex.py
  norse/torch/module/lif_ex.py
  norse/torch/module/lsnn.py
  norse/torch/module/regularization.py
  norse/torch/module/test/test_lsnn.py
  requirements-dev.txt
Labels: enhancement

#158 Model documentation
  README.md
  docs/Makefile
  docs/source/hardware.rst
  docs/source/index.rst
  docs/source/installing.rst
  docs/source/learning.rst
  docs/source/spiking.rst
  docs/source/started.rst
  docs/source/tasks.rst
  docs/source/working.rst
  norse/task/__init__.py
  norse/torch/module/lif.py
  norse/torch/module/lif_adex.py
  norse/torch/module/lif_ex.py
  norse/torch/module/lif_mc.py
  norse/torch/module/sequential.py
Labels: documentation, enhancement
