Repository norse/norse, pull requests merged in 2020-10, with the labels that each got.

#123 VGG models lifted to SNN models
  norse/torch/models/LICENSE.vgg
  norse/torch/models/test/test_vgg.py
  norse/torch/models/vgg.py
Labels: enhancement, model

#124 Feature sequential
  norse/torch/module/sequential.py
  norse/torch/module/test/test_sequential.py
Labels: enhancement

#127 Issue 125 gradient
  norse/torch/models/test/test_vgg.py
  norse/torch/module/coba_lif.py
  norse/torch/module/leaky_integrator.py
  norse/torch/module/lif.py
  norse/torch/module/lif_adex.py
  norse/torch/module/lif_ex.py
  norse/torch/module/lif_refrac.py
  norse/torch/module/lsnn.py
  norse/torch/module/test/test_coba.py
  norse/torch/module/test/test_li.py
  norse/torch/module/test/test_lif.py
  norse/torch/module/test/test_lif_adex.py
  norse/torch/module/test/test_lif_ex.py
  norse/torch/module/test/test_lif_mc.py
  norse/torch/module/test/test_lif_mc_refrac.py
  norse/torch/module/test/test_lif_refrac.py
  norse/torch/module/test/test_lsnn.py
  norse/torch/module/test/test_training.py
Labels: bug

#128 Increase coverage
  norse/torch/functional/test/test_threshold.py
  norse/torch/functional/test_lsnn.py
  norse/torch/functional/threshold.py
Labels: bug, coverage

#132 Add further threshold tests, fix bugs
  norse/torch/functional/spiking_vector_quantization.py
  norse/torch/functional/stdp_sensor.py
  norse/torch/functional/test/test_stdp_sensor.py
  norse/torch/functional/test/test_superspike.py
  norse/torch/functional/test/test_threshold.py
  norse/torch/functional/threshold.py
  norse/torch/module/__init__.py
  norse/torch/module/if_current_encoder.py
Labels: coverage

#135 Add integration test for lif correlation
  norse/torch/module/test/test_lif_correlation.py
Labels: coverage

#134 Mobilenet-v2 port
  norse/torch/models/LICENSE.torchvision
  norse/torch/models/mobilenet.py
  norse/torch/models/test/test_mobilenet.py
  norse/torch/models/vgg.py
Labels: enhancement, model

#136 Increase coverage
  norse/torch/functional/correlation_sensor.py
  norse/torch/functional/encode.py
  norse/torch/functional/heaviside.py
  norse/torch/functional/lif.py
  norse/torch/functional/regularization.py
  norse/torch/functional/test/test_encode.py
  norse/torch/functional/test/test_lif.py
  norse/torch/functional/test/test_logical.py
  norse/torch/functional/test/test_regularization.py
  norse/torch/functional/threshold.py
  norse/torch/models/mobilenet.py
  norse/torch/models/test/test_mobilenet.py
  norse/torch/models/test/test_vgg.py
  norse/torch/models/vgg.py
  norse/torch/module/test/test_coba.py
  norse/torch/module/test/test_li.py
  norse/torch/module/test/test_lif.py
  norse/torch/module/test/test_lif_adex.py
  norse/torch/module/test/test_lif_correlation.py
  norse/torch/module/test/test_lif_ex.py
  norse/torch/module/test/test_lif_mc.py
  norse/torch/module/test/test_lif_mc_refrac.py
  norse/torch/module/test/test_lif_refrac.py
Labels: coverage

#138 Added torch-like module/functional imports
  README.md
  norse/__init__.py
  norse/torch/__init__.py
  norse/torch/functional/__init__.py
  norse/torch/module/__init__.py
  norse/torch/module/encode.py
Labels: enhancement

#139 Feature 121 consistent api
  .gitignore
  norse/task/cifar10.py
  norse/torch/__init__.py
  norse/torch/functional/leaky_integrator.py
  norse/torch/models/__init__.py
  norse/torch/module/coba_lif.py
  norse/torch/module/leaky_integrator.py
  norse/torch/module/lif.py
  norse/torch/module/lif_adex.py
  norse/torch/module/lif_correlation.py
  norse/torch/module/lif_ex.py
  norse/torch/module/lif_mc.py
  norse/torch/module/lif_mc_refrac.py
  norse/torch/module/lif_refrac.py
  norse/torch/module/lsnn.py
  norse/torch/module/test/test_encode.py
  norse/torch/module/test/test_leaky_integrator.py
  norse/torch/module/test/test_li.py
  norse/torch/module/test/test_lif.py
  norse/torch/module/test/test_lif_adex.py
  norse/torch/module/test/test_lif_ex.py
  norse/torch/module/test/test_lsnn.py
  norse/torch/module/test/test_regularization.py
Labels: enhancement

#133 STDP steppers for FF and conv2d
  .gitignore
  norse/torch/functional/stdp.py
  norse/torch/functional/test/test_stdp.py
  requirements-dev.txt
  requirements.txt
Labels: enhancement
