Repository norse/norse, pull requests merged in 2021-09, with the labels that each got.

#252 Remove trailing symbol in notebook examples link.
  docs/index.md
Labels: documentation

#253 Added build tests for windows and mac
  .github/workflows/publish_pypi.yml
  .github/workflows/pythonpackage.yml
  requirements-dev.txt
  setup.py
Labels: installation, windows

#257 Expand introduction to spiking systems
  docs/pages/spiking.ipynb
Labels: documentation

#258 Fixed issue with sequential forward hooks
  norse/torch/module/sequential.py
  norse/torch/module/test/test_sequential.py
Labels: bug

#261 Fixed bug where LIF would crash if v_leak was scalar
  norse/torch/module/lif.py
  norse/torch/module/test/test_lif.py
  norse/torch/module/test/test_snn.py
Labels: bug

#265 Fixed #262 and improved (L)IF docs
  docs/_toc.yml
  docs/images/lif_integration.gif
  docs/norse.torch.functional.rst
  docs/norse.torch.rst
  docs/pages/learning.rst
  docs/pages/working.ipynb
  norse/torch/module/lif_mc.py
  norse/torch/module/lif_mc_refrac.py
Labels: documentation
