Repository norse/norse, pull requests merged in 2022-05, with the labels that each got.

#322 Build docker image only on push to master
  .github/workflows/docker_build.yml
Labels: ci/tooling

#321 Feature spikes to times decoder
  norse/torch/functional/spikes_to_times_decoder.py
  norse/torch/functional/test/test_spikes_to_times_decoder.py
  norse/torch/module/__init__.py
  norse/torch/module/spikes_to_times_decoder.py
  norse/torch/module/test/test_spikes_to_times_decoder.py
Labels: enhancement

#327 fix: Changed inplace spike latency encode to non-inplace
  norse/torch/functional/encode.py
Labels: bug
